name: Request_Site
description: Request support for a new site

title: "[Request] <site-domain>"
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Note #1: AdsBypasser DOES NOT bypass reCAPTCHA

        Note #2: Please update the issue title to include the site domain:
        `[Request] example.com`

  - type: input
    id: site-domain
    attributes:
      label: Site Domain
      description: What is the domain of the site you want to be supported?
      placeholder: example.com
    validations:
      required: true

  - type: input
    id: full-link
    attributes:
      label: Full Link
      description: Please provide a full link from this site
      placeholder: https://example.com/redirect-link
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of why you'd like this site to be supported
      placeholder: Describe the site and why it should be supported
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Before submitting:
        1. Please check if there is an existing ticket open for the same site.
