name: Release

on:
  push:
    tags:
      - "v*" # Triggers on version tags like v7.32.0

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history for proper tagging

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build userscripts
        run: npm run build

      - name: Generate GitHub Pages content
        run: npm run ghpages

      - name: Deploy to GitHub Pages with Tag
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/ghpages
          tag_name: ${{ github.ref_name }}
          tag_message: ${{ github.ref_name }}
